# Generated by Django 3.2.16 on 2023-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230105_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='year',
            field=models.IntegerField(),
        ),
    ]
