# Generated by Django 3.2.16 on 2023-01-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_thread_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='excerpt',
        ),
    ]
