# Generated by Django 3.2.16 on 2023-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_thread_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
